### ISSUE TITLE
profile page has extra whitespace

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-theme-community#19]
on community
![image](https://user-images.githubusercontent.com/2583394/145100123-21b8e573-5966-44c3-91b3-99e09cecac59.png)

default persona
![image](https://user-images.githubusercontent.com/2583394/145100159-07c348d0-1951-4ca7-b32d-ca5c8912b890.png)

**Comment by julianlam** [comment]
Looks like the account cover position does not take the new header into account:

![image](https://user-images.githubusercontent.com/923011/145103843-c99c8da9-4e50-45e0-b827-30ab20a176aa.png)

Fix would be to change this calculation to use the pre-calculated panel offset:

`document.documentElement.style.getPropertyValue('--panel-offset')`
